# Generated by Django 3.2 on 2022-08-26 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='menu',
            field=models.CharField(blank=True, choices=[('sales', 'sales'), ('orders', 'orders'), ('products', 'products'), ('customers', 'customers'), ('calender', 'calender')], max_length=50, null=True, verbose_name='Menu alanı'),
        ),
        migrations.AddField(
            model_name='person',
            name='position',
            field=models.CharField(blank=True, choices=[('bottom_left', 'bottom_left'), ('top_right', 'top_right'), ('top_left', 'top_left')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='show',
            field=models.BooleanField(default=False, verbose_name='Gösterilsin mi'),
        ),
    ]
