# Generated by Django 3.2 on 2022-08-28 20:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mainApp', '0002_auto_20220826_2331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='menu',
            field=models.CharField(blank=True, choices=[('calender', 'calender'), ('orders', 'orders'), ('customers', 'customers'), ('sales', 'sales'), ('products', 'products')], max_length=50, null=True, verbose_name='Menu alanı'),
        ),
        migrations.AlterField(
            model_name='person',
            name='position',
            field=models.CharField(blank=True, choices=[('bottom_left', 'bottom_left'), ('top_left', 'top_left'), ('top_right', 'top_right')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profil', to=settings.AUTH_USER_MODEL),
        ),
    ]
