# Generated by Django 3.2 on 2022-08-28 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0003_auto_20220828_2316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='menu',
            field=models.CharField(blank=True, choices=[('customers', 'customers'), ('products', 'products'), ('sales', 'sales'), ('orders', 'orders'), ('calender', 'calender')], max_length=50, null=True, verbose_name='Menu alanı'),
        ),
        migrations.AlterField(
            model_name='person',
            name='position',
            field=models.CharField(blank=True, choices=[('top_right', 'top_right'), ('bottom_left', 'bottom_left'), ('top_left', 'top_left')], max_length=50, null=True),
        ),
    ]
