# Generated by Django 3.2 on 2022-08-29 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0004_auto_20220828_2350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='menu',
            field=models.CharField(blank=True, choices=[('orders', 'orders'), ('calender', 'calender'), ('products', 'products'), ('sales', 'sales'), ('customers', 'customers')], max_length=50, null=True, verbose_name='Menu alanı'),
        ),
        migrations.AlterField(
            model_name='person',
            name='position',
            field=models.CharField(blank=True, choices=[('bottom_left', 'bottom_left'), ('top_right', 'top_right'), ('top_left', 'top_left')], max_length=50, null=True),
        ),
    ]
